#配置项目名
spring:
  application:
    admin:
      enabled: true
    name: GoodsManager
  security:
    user:
      name: admin
      password: admin123
  datasource:
    url:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: ESmElsXuj3ls8Fq
    hikari:
      catalog: GoodsDB
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        format_sql: true
    database: sql_server
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    rest:
      enable-enum-translation: true
  boot:
    admin:
      client:
        url: http://localhost:9527/admin
      ui:
        title: 人类恶管理中心
        available-languages: zh
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>${spring.boot.admin.ui.title}</span>
      context-path: /admin

server:
  port: 9527

management:
  endpoints:
    web:
      exposure:
        include: '*'
     # base-path: /admin/actuator
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      path: C:\